### ISSUE TITLE
WSGI interface for hosting an agent

### ISSUE THREAD

**Issue by andrewwhitehead** [bcgov/aries-vcr#181]
Universities and other web hosting providers often allow users to run custom Python applications using the WSGI interface. Such support would require refactoring of the agent's initialization procedure, as the inbound transports would not be configurable in this situation except for HTTP-based transports.

To support an admin transport, websocket, or hosting of UI resources the connection would likely use path prefixes to distinguish services.

Configuration parameters would likely need to be loaded from a file or the environment, instead of the command line as the application is initialized by directly loading a Python module.

**Comment by mhailstone** [comment]
It would be nice abstract away the indy message handling from the transport, so that the indy handling could be a module imported on its own and the transport layer could configure and wire-up how to get the indy message handling module the information coming in on whatever wire transport/routing mechanism that needs to exist. The hope would be to reuse the same indy messaging handler and pluggable module under any wire transport or routing framework underneath the wire transport: a bluetooth transport handler, or http server (i.e. django, websocket, wsgi, etc.), or any some other wire transport.

**Comment by swcurran** [comment]
Icebox-ing this, but if the bc-registries task gets done (blocker) than this will be an easy follow on.

**Comment by swcurran** [comment]
Closing this issue as this needs to be applied to ACA-Py and I can't transfer it.  I'm not sure if this is still needed, so if those seeing this think it is a good ACA-Py issue, please open there.

Thanks
