### ISSUE TITLE
Add data file and script for loading test data into dev instance

### ISSUE THREAD

**Issue by swcurran** [bcgov/aries-vcr#416]
Add a data file of organizations and a script (ideally called from `./manage`) to issue (load) data into a fresh instance of a dev Credential Registry.  Add instructions for how to run.

Ideal is that we be able to go into a generic Credential Registry and start the Credential Registry, load it with useful data and be able to interact with the interface - using an API or a the web UI.

**Comment by swcurran** [comment]
@esune @ianco  - what would it take to do this?  Is this a reasonable task to add?  It's really hard to test the changes that are happening without this.

Is there a way to do it now that is not scripted but that we can provide info on?  Perhaps we could just do a DB backup and restore without having to setup issuers?

Thanks

**Comment by esune** [comment]
To load data into ICOB, an instance of the BCReg agent needs to be running since it is through bcreg that all the data is created.

We currently load data "sucking" it in from the bc registries test database, but we could either create a task with a data file in the von-bc-registries-agent project with a limited number of corps - we just need to be aware that data will be in GitHub (it may or may not be an issue at all though).
