### ISSUE TITLE
Misleading relationship links 

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/aries-vcr#489]
Found in:
- 87c6bd423f537231d36ffa8ae8c26f91247f3b9f

Example:
- https://orgbook-dev.pathfinder.gov.bc.ca/en/organization/demo.verified_person.registries.ca/VPCLUTCHLULANI

The links in the **Related To** section link to the related company registration pages as expected:
![image](https://user-images.githubusercontent.com/10504350/80529837-f1794d80-894c-11ea-9f2c-21e839dbe12b.png)

However the "same" links in the **Credentials** section link to Verified Person relationship record:
![image](https://user-images.githubusercontent.com/10504350/80529987-3604e900-894d-11ea-81fd-726a46b040d1.png)

**Comment by ianco** [comment]
Not a bug, that's how the UI is defined.

In the timeline the link is to the credential (which in the case of a relationship is a link to the Relationship credential).

Same applies for DBA relationships.

**Comment by WadeBarnes** [comment]
Any way we can make it more intuitive?  I see this perceived inconsistency causing a great deal of confusion.

**Comment by ianco** [comment]
I think this falls under the general category of UI design, which has been an issue since day 1.

We've talked about getting a resource in to do a UX redesign but that's never been a priority.

I'd be happy to make changes if you have any specific recommendations but I don't know that this is a show-stopper for getting the latest aries-vcr into production.

**Comment by WadeBarnes** [comment]
Sounds like we should review with @swcurran and @jljordan42

**Comment by swcurran** [comment]
@jljordan42 -- FYI - a UX issue that is going onto the backlog.
