### ISSUE TITLE
Overlapping credential timelines

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/aries-vcr#490]
Found in:
- 87c6bd423f537231d36ffa8ae8c26f91247f3b9f

Example Data:
- https://orgbook-test.pathfinder.gov.bc.ca/en/organization/registration.registries.ca/BC0337062

Observed:
In this example case the credential timeline for the first expired credential overlap the timeline for the second expired credential.  When you hover over the first, it hides the second; refer to the screen shots below.

Expected:
The credential timelines don't overlap.

![image](https://user-images.githubusercontent.com/10504350/80601420-a742ab80-89e2-11ea-8186-fed6cc43a857.png)

![image](https://user-images.githubusercontent.com/10504350/80601475-b7f32180-89e2-11ea-858b-6cedabc2175a.png)

**Comment by WadeBarnes** [comment]
Other example(s):
- https://orgbook-test.pathfinder.gov.bc.ca/en/organization/registration.registries.ca/BC0496513

**Comment by ianco** [comment]
BC0337062

**Comment by ianco** [comment]
Not able to duplicate this issue.  I tested loading this company on my local and the credentials loaded correctly, with the expected issue and expiry dates.

There are 3 possibilities:

1. Concurrency issue - two separate pods adding credentials to the same company at the same time (I think this is the most likely, although the issuer script tries to "batch" credentials for the same company together, so that they are processed serially, so this *shouldn't* happen)

2. These credentials were created around Nov 26, 2019 - there may have been a bug in the code at that time which has since been fixed (although I did a quick scan of the git commits and there was nothing obvious for this particular issue)

3. There is a bug in the existing code which happens sporadically and I just haven't tested enough, or I have too small a sample dataset on my local to get the issue to recur.

**Comment by ianco** [comment]
Putting this one back in the backlog for now ...

**Comment by WadeBarnes** [comment]
I was referring more to the display of the credentials.  If you look at the second screenshot you can see the second credential in the timeline is hidden when you hover over the first.

**Comment by ianco** [comment]
Yes that's because the expiry date isn't getting set properly, so the credentials have overlapping effective periods.

The expiry date is set by OrgBook when it receives the credential; the effective date is set by the issuer.

**Comment by ianco** [comment]
The expiry date is displayed in the red "Expired" box on the credential screen, if the credential is expired
